### ISSUE TITLE
Wrong variables for Orcaslicer start gcode

### ISSUE THREAD

**Issue by cbaugher** [3DPrintDemon/Demon_KLIPPER_Essentials#4]
In demon_print_start_end_v2.4.cfg the variables in the PRINT_START line for Orcaslicer are wrong.

# PRINT_START EXTRUDER=[first_layer_temperature[initial_extruder]] BED=[first_layer_bed_temperature] HEIGHT=[first_layer_height] LAYER=[layer_height] FILAMENT=[filament_type] EXTRUSION=[outer_wall_line_width]

These are Prusaslicer variables and don't work for Orca.

**Comment by cbaugher** [comment]
I did know that Orca was derived from Prusa, so I was expecting them to be the same.  But for some reason they are not on my version of Orca (1.9.0).

If I check the tool tip for the initial layer hotend temp in Orca it shows this:

![image](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/12405888/d6122946-1085-41e9-ab05-8987e24e3ac0)

Vs Prusa:

![image](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/12405888/076f4747-0d71-486a-a603-34995c6fa8c6)


Are there different flavors of Orca maybe?

**Comment by 3DPrintDemon** [comment]
Well that is kinda interesting as I just checked a gcode file sliced by Orca 1.9.0 & it has both "first_layer_temperature" & "nozzle_temperature_initial_layer" listed with the correct temperature in my file. I guess that's why it's been working on my system then. I'll change the files to reflect the tooltip you posted there just so it'll work for everyone.
Thanks for noticing this, its this is why I alway like to check stuff when someone reports something not working even if it does here!
![Screenshot 2024-01-17 at 18 48 15](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/122202359/ccb782ec-1c31-4001-85c0-c6e98c44b338)
![Screenshot 2024-01-17 at 18 48 33](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/122202359/5fe76d01-bf53-4ca8-b2c5-516ecc42dd1a)

**Comment by cbaugher** [comment]
Weird.  I just checked a sliced file on mine and it doesn't have "first_layer_temperature" listed at all.  What's up with that?
There must be something changing the output variables.  I wonder if it's related to a setting somewhere?

This is the start gcode line I ended up with.

PRINT_START EXTRUDER=[nozzle_temperature_initial_layer] BED=[hot_plate_temp_initial_layer] HEIGHT=[initial_layer_print_height] LAYER=[layer_height] FILAMENT=[filament_type] EXTRUSION=[outer_wall_line_width]

**Comment by 3DPrintDemon** [comment]
yeah so strange, something odd going on there I think. Maybe it's a different OS system version of Orca, or like you said having to do with an option or something.

Yea can confirm thats exactly what I've got here too for an updated line. Just testing a print but it should work. will update files in a few minutes

**Comment by 3DPrintDemon** [comment]
Yeah I'll have a look, I've not seen anything before but saying that they do have over 800 open issues!
Definitely worth mentioning it, I tbh really appreciate it as the error was not reproducible here, so as far as I knew it was all ok & the same for all versions/setups of Orca. I guess not so much! 
I'll sure keep trying! Glad we got it sorted out there!

**Comment by 3DPrintDemon** [comment]
Marking as Closed
