### ISSUE TITLE
'Unknown command: "AUTO_5"' when trying to run Auto 5 Bed Mesh Builder

### ISSUE THREAD

**Issue by sgwestrip** [3DPrintDemon/Demon_KLIPPER_Essentials#6]
Immediately after hitting the macro button I get this error in the Console window. I have double-checked the instructions and I seem to have done everything correctly.

**Comment by 3DPrintDemon** [comment]
Please teach closed issues before posting. This has been fixed as was due to naming issue. Please update your files.
https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/issues/2

**Comment by sgwestrip** [comment]
I only downloaded the files 1 hour ago

**Comment by sgwestrip** [comment]
Interesting. Between when I raised the issue and now the mesh_bulider_v1.0.cfg has changed! It now has the new variable names.

**Comment by 3DPrintDemon** [comment]
Yeah odd as the mesh builder file was updated last week and has not changed or been updated since then. Maybe your browser cached the page & just reloaded it now?
![Screenshot 2024-01-19 at 15 13 11](https://github.com/3DPrintDemon/Demon_KLIPPER_Essentials/assets/122202359/3a48d8d6-6227-480b-94dd-74205dea4738)

Ah ok the assets were outdated, removed for now to avoid further confusion. Sorry about that.
Please download from the main page.
